millionaire/accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login, logout


urlpatterns = [
    url(r'^$',views.HomeView.as_view(), name='home'),
    url(r'^login/$', login, {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout/$', logout, {'template_name': 'accounts/logout.html'}, name='logout'),
    url(r'^register/$', views.register, name='register'),
]

millionaire/game/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^end/$', views.end, name='end'),
    url(r'^start/$', views.GamePlay.as_view(), name='start'),
    url(r'^won/(?P<score>\d+)$', views.won, name='won'),
]

millionaire/millionaire/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from game import views

urlpatterns = [
    url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls',namespace='accounts')),
    url(r'^game/', include('game.urls',namespace="game")),
]

millionaire/game/models.py
from __future__ import unicode_literals

from django.db import models

class Question(models.Model):

    question = models.CharField(max_length=1000)
    choice_options = models.CharField(max_length=1000,help_text=("Coma separated string of all possible variants"))
    correct_answers = models.CharField(max_length=1000,help_text=("Coma separated string of all correct answers"))
    score = models.IntegerField()

    def __str__(self):
        return "Question with score " + str(self.score)

millionaire/accounts/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.views.generic import TemplateView

# Create your views here.

class HomeView(TemplateView):
    template_name='accounts/home.html'



def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/account/login')
        else:
            return HttpResponse("not valid info")
    else:
        form = UserCreationForm()
        args = {'form' : form}
        return render(request,'accounts/reg_form.html', args)

millionaire/game/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.views.generic import TemplateView
from models import Question
import random

# Create your views here.

class GamePlay(TemplateView):
    template_name='game/start.html'

    def get_context_data(self, **kwargs):
        context = super(GamePlay, self).get_context_data(**kwargs)

        questions = Question.objects.all()
        if 'used_questions' in self.request.session:
            questions = questions.exclude(id__in = self.request.session['used_questions'])
        else:
            self.request.session['used_questions'] = []

        question = random.choice(questions)
        self.request.session['used_questions'].append(question.id)

        context['question'] = question.question
        context['answers'] = question.choice_options.split(",")
        self.request.session['correct_answers'] = question.correct_answers.split(",")
        self.request.session['current_question_id'] = question.pk
        context['correct_answers'] = question.correct_answers.split(",")
        return context
    def post(self,request):

        answers = request.POST.getlist('checks')
        correct_answers = request.session['correct_answers']



        if not 'questions_count' in request.session:
            request.session['questions_count'] = 0
        elif request.session['questions_count'] > 5:
            request.session['questions_count'] = 0

            score = str(request.session['score'])
            request.session['score'] = 0
            request.session['used_questions'] = []
            return redirect('/game/won/' + score)
        else:
            request.session['questions_count'] += 1

        if all(elem in correct_answers  for elem in answers):
            if not 'score' in request.session:
                request.session['score'] = Question.objects.filter(pk=request.session['current_question_id']).get().score
            else:
                request.session['score'] += Question.objects.filter(pk=request.session['current_question_id']).get().score
            return redirect('/game/start')

        request.session['questions_count'] = 0
        if not 'score' in request.session:
            request.session['score'] = 0
        score = request.session['score']
        request.session['score'] = 0
        request.session['used_questions'] = []

        context = {'correct_answers':correct_answers,
                   'score':score,
                   }
        return render(self.request, 'game/end.html', context)


def login_redirect(request):
    return redirect('/account/')

def start(request):
    answer_list = ['first answer','second answer','etc...']
    args = {'question': "test question", 'answers': answer_list}
    return render(request,'game/start.html', args)

def end(request):
    return render(request,'game/end.html')

def won(request, score):
    return render(request,'game/won.html',{'score':score})

millionaire/accounts/templates/accounts/home.html
{% extends 'base.html' %}

<h1>Home</h1>
{% block head %}
    <title>Home page</title>
{% endblock %}


{% block body %}
    <div class="container">
        {% if user.is_authenticated %}
            <div class="container">
                <a href="{% url 'game:start' %} " class="btn btn-info" role="button">Start Game</a>
            </div>

        {% else %}
        <h1>Please login to start a game</h1>
        {% endif %}
    </div>

{% endblock %}

millionaire/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block body %}
    <div class="container">
        <h1>Welcome to <b></h1>
        <p>
            You can login here
        </p>
        <h2>Login</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Login</button>
        </form>
    </div>
{% endblock %}

millionaire/accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block body %}
    <div class="container">
        <h1>Logged out<b></h1>
        <p>
            Please login to start a game
        </p>

    </div>
{% endblock %}

millionaire/accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}

{% block body %}
    <div class="container">
    <h1>Register</h1>
         <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
        </form>
    </div>

{% endblock %}

millionaire/accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    {% block head %}
    <title>Base</title>
    {% endblock %}
</head>
<body>
    <br>
    <div class="container">

      <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            {% if user.is_authenticated %}
            <ul class="nav navbar-nav">
              <li><a href="{% url 'accounts:home' %}">Home</a></li>
              <li><a href="{% url 'accounts:logout' %}">Log out</a></li>
            </ul>
            {% else %}
            <ul class="nav navbar-nav">
              <li><a href="{% url 'accounts:home' %}">Home</a></li>

            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
                <li><a href="{% url 'accounts:register' %}">Register</a></li>
            </ul>
              {% endif %}
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>


    </div> <!-- /container -->
    {% block body %}
        <h1>Base</h1>
    {% endblock %}
</body>
</html>

millionaire/game/templates/game/end.html
{% extends 'base.html' %}

{% block head %}
    <title>Game</title>
{% endblock %}


{% block body %}
    <div class="container">
            <div class="container">
                <h1>Game over</h1>
                <h3>Correct answer is
                    {% for ans in correct_answers %}
                    {{ ans }}
                    {% endfor %}
                </h3>
                <h3>Score: {{ score }}</h3>
                <a href="{% url 'game:start' %} " class="btn btn-info" role="button">New Game</a>
            </div>
    </div>

{% endblock %}

millionaire/game/templates/game/start.html
{% extends 'base.html' %}

{% block head %}
    <title>Game</title>
{% endblock %}


{% block body %}
    <div class="container">
        {% if user.is_authenticated %}
            <div class="container">
                <h1>{{ question }}</h1>
                <form method="post">
                {% csrf_token %}
                    {% for ans in answers %}
                        <ul>
                        <div class="checkbox">
                            <label><input type="checkbox" name="checks" value="{{ ans }}">{{ ans }}</label>
                        </div>
                        </ul>
                    {% endfor %}
{#                    {% for ans in correct_answers %}#}
{#                        <ul>#}
{#                            {{ ans }}#}
{#                        </ul>#}
{#                    {% endfor %}#}
                    <ul>
                        <button class="btn btn-info" type="submit">Submit</button>
                    </ul>
                </form>

            </div>

        {% else %}
        <h1>Please login to start a game</h1>
        {% endif %}
    </div>

{% endblock %}

millionaire/game/templates/game/won.html
{% extends 'base.html' %}

{% block head %}
    <title>Winner!!!</title>
{% endblock %}


{% block body %}
    <div class="container">
            <div class="container">
                <h1>Congratulations, You won!!</h1>
                <h2>Your score is {{ score }}</h2>
                <a href="{% url 'game:start' %} " class="btn btn-info" role="button">New Game</a>
            </div>
    </div>

{% endblock %}